server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/** 
        - id: payment
          uri: http://localhost:8082
          predicates:
            - Path=/payments/** 
        - id: delivery
          uri: http://localhost:8083
          predicates:
            - Path=/deliveries/** 
        - id: statusview
          uri: http://localhost:8084
          predicates:
            - Path= /statusViews/**
        - id: coupon
          uri: http://localhost:8085
          predicates:
            - Path=/coupons/** 
        - id: location
          uri: http://localhost:8086
          predicates:
            - Path=/locations/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/** 
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/** 
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveries/** 
        - id: statusview
          uri: http://statusview:8080
          predicates:
            - Path= /statusViews/**
        - id: coupon
          uri: http://coupon:8080
          predicates:
            - Path=/coupons/** 
        - id: location
          uri: http://location:8080
          predicates:
            - Path=/locations/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
